### PR TITLE
Bug fix #213 and #208

### LINKED ISSUE #213: fetchAssoc() fails with freshly created Reader
## Issue summary

I need to pre-process a CSV file that was given to me that contains a number of columns with duplicate names. In order to process this file I am creating a reader, writing some columns with a writer, and then getting a reader:

```php
$reader = Reader::createFromPath('path/to/file.csv');
$write = Writer::createFromStream(fopen('php://temp', 'r+'));
$columns_to_extract = [1, 2, 3, 4, 5, 43];

foreach ($reader->fetch() as $row) {
    $write->insertOne(array_intersect_key($row, $columns_to_extract));
}

$reader = $write->newReader()->setOffset(0);
```

And then I pass the `$reader` into another class that uses `fetchAssoc()`:

```php
function process(Reader $csv)
{
    foreach ($csv->fetchAssoc() as $row) {
        // do stuff with row
    }
}
```

This works fine for other CSVs, but as soon as I add this pre-processing step, I get the following error:

```
InvalidArgumentException: the specified row does not exist or is empty in importer/vendor/league/csv/src/Reader.php on line 338

Call Stack:
    0.0002     233496   1. {main}() importer/bin/import:0
    0.0255    1522728   2. League\Csv\Reader->fetchAssoc() importer/bin/import:17
    0.0255    1522928   3. League\Csv\Reader->getAssocKeys() importer/vendor/league/csv/src/Reader.php:247
    0.0255    1523208   4. League\Csv\Reader->getRow() importer/vendor/league/csv/src/Reader.php:281
```

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Csv version | 8.2.0 |
| PHP/HHVM version | 5.6.29 |
| OS Platform | osx  |

## Standalone code, or other way to reproduce the problem

*See description.*

### Expected result

No error.

### Actual result

Exception thrown.

### PR DESCRIPTION
**Pull request by nyamsprod**
- Remove the @deprecate message from the Reader class #208
- Bug fix internal Reader::getRow when used with a StreamIterator #213

### CODE REVIEW

File: src/Modifier/StreamIterator.php [hunk 1]
```diff
@@ -156,18 +156,17 @@ public function setFlags($flags)
      * @param array  $fields
      * @param string $delimiter
      * @param string $enclosure
-     * @param string $escape
```
Comment (shadowhand) [inline src/Modifier/StreamIterator.php]: You removed the `$escape` type hint, but the param is still available in the method.

File: src/Modifier/StreamIterator.php [hunk 2]
```diff
@@ -156,18 +156,17 @@ public function setFlags($flags)
...
      *
      * @return int
      */
-    public function fputcsv(array $fields, $delimiter = null, $enclosure = null, $escape = null)
+    public function fputcsv(array $fields, $delimiter = ',', $enclosure = '"', $escape = '\\')
```
Comment (shadowhand) [inline src/Modifier/StreamIterator.php]: This changes the public interface and should not be part of a bugfix.

File: src/Reader.php [hunk 3]
```diff
@@ -329,19 +317,23 @@ protected function isValidKey($value)
...
+        }
+
+        $bom_length = mb_strlen($this->getInputBOM());
+        $row[0] = mb_substr($row[0], $bom_length);
+        if ($this->enclosure == mb_substr($row[0], 0, 1) && $this->enclosure == mb_substr($row[0], -1, 1)) {
+            $row[0] = mb_substr($row[0], 1, -1);
         }
 
-        return str_getcsv($line, $this->delimiter, $this->enclosure, $this->escape);
+        return $row;
```
Comment (shadowhand) [inline src/Reader.php]: The expected return value for this method is an array, and now appears to be a string.

File: src/Modifier/StreamIterator.php (hunk 2 above)
Comment (nyamsprod) [inline src/Modifier/StreamIterator.php]: it should be part of bugfix because it aligns the StreamIterator to how SplFileObject and fputcsv works. StreamIterator must be align to SplFileObject and it did no align.

Comment (nyamsprod) [inline src/Modifier/StreamIterator.php]: StreamIterator is marked as `@internal` so anyone using it in public API exposes himself to harm.

File: src/Reader.php (hunk 3 above)
Comment (nyamsprod) [inline src/Reader.php]: no $row is always an array

File: src/Modifier/StreamIterator.php (hunk 1 above)
Comment (nyamsprod) [inline src/Modifier/StreamIterator.php]: yep typo error from my part.. I'll correct that
